version: '3.8'

services: 
  db:
    image: postgres:12
    volumes: 
      - pg_data:/var/lib/postgresql/data/
    environment: 
      POSTGRES_PASSWORD: admin123
      POSTGRES_USER: postgres
      POSTGRES_DB : medusa_light_db
  web:
    container_name: medusa_light_web
    build:
      context: ./
      dockerfile: Dockerfile
    command: bash -c "python /usr/src/medusa_light/manage.py migrate --noinput &&
             python /usr/src/medusa_light/manage.py runserver 0.0.0.0:8000"
    volumes: 
      - .:/usr/src/medusa_light
    ports: 
      - 8000:8000

    depends_on: 
      - db
volumes: 
  pg_data: